import http from 'k6/http';
import { check, sleep } from 'k6';

// k6 execution configuration simulating a constant 1,000 requests/sec (RPS)
export const options = {
  scenarios: {
    fee_bump_stress: {
      executor: 'constant-arrival-rate',
      rate: 1000,
      timeUnit: '1s', // 1000 requests per second
      duration: '3m', // Run for 3 minutes to measure peak CPU and memory usage
      preAllocatedVUs: 200, // Start with 200 pre-allocated virtual users
      maxVUs: 2000, // Allow scaling up to 2000 VUs if response times degrade
    },
  },
  thresholds: {
    // Quality of service thresholds
    http_req_duration: ['p(95)<300', 'p(99)<1000'], // 95% of requests under 300ms, 99% under 1s
    http_req_failed: ['rate<0.01'],                  // Request failure rate below 1%
  },
};

export default function () {
  const baseUrl = __ENV.API_URL || 'http://localhost:3000';
  const url = `${baseUrl}/fee-bump`;
  
  // Base64 encoded signed transaction XDR representing a payment transaction needing a fee bump.
  // This value is automatically generated by our Rust tests and works with the local environment.
  const payload = JSON.stringify({
    xdr: __ENV.XDR || 'AAAAAgAAAACSpS9o+jZ+GfM3y+FmP5g4kNz/t/L3U7QjM2m0j53u9QAAAGQAADhpAAAAAAAAACoAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAHAAAAAAAAAACm2Q2F+066S5kGZ8G14y6l5sX7b8UAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC',
    submit: false,
  });

  const params = {
    headers: {
      'Content-Type': 'application/json',
      'X-API-Key': __ENV.API_KEY || 'paymaster-pro-demo-key',
    },
  };

  // Perform the POST request to the fee-bump endpoint
  const res = http.post(url, payload, params);

  // Validate the response
  check(res, {
    'status is 200': (r) => r.status === 200,
    'response has xdr': (r) => {
      try {
        const json = JSON.parse(r.body);
        return !!json.xdr;
      } catch (e) {
        return false;
      }
    },
  });
}
