name: fluid_sdk
description: A Flutter SDK for interacting with Fluid servers.
version: 0.1.0
homepage: https://github.com/stellar-fluid/fluid

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stellar_sdk: ^0.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0