apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlm-paymaster.fullname" . }}-node-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xlm-paymaster.labels" . | nindent 4 }}
    app.kubernetes.io/component: node-api
spec:
  type: {{ .Values.nodeApi.service.type }}
  selector:
    {{- include "xlm-paymaster.selectorLabels" (dict "root" . "component" "node-api") | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.nodeApi.service.port }}
      targetPort: http
