apiVersion: v1
kind: Service
metadata:
  name: {{ include "xlm-paymaster.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xlm-paymaster.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "xlm-paymaster.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: postgres
