import os
from locust import task, between
from locust.contrib.fasthttp import FastHttpUser

class PaymasterLoadTestUser(FastHttpUser):
    # Minimal pacing delay to simulate fast-acting clients and high request frequency
    wait_time = between(0.001, 0.005)

    @task
    def post_fee_bump(self):
        url = "/fee-bump"
        
        # Base64 encoded signed transaction XDR representing a payment transaction needing a fee bump.
        # This value is automatically generated by our Rust tests and works with the local environment.
        xdr = os.getenv("XDR", "AAAAAgAAAACSpS9o+jZ+GfM3y+FmP5g4kNz/t/L3U7QjM2m0j53u9QAAAGQAADhpAAAAAAAAACoAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAAHAAAAAAAAAACm2Q2F+066S5kGZ8G14y6l5sX7b8UAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC")
        
        payload = {
            "xdr": xdr,
            "submit": False
        }
        
        headers = {
            "Content-Type": "application/json",
            "X-API-Key": os.getenv("API_KEY", "paymaster-pro-demo-key")
        }
        
        with self.client.post(url, json=payload, headers=headers, catch_response=True) as response:
            if response.status_code == 200:
                try:
                    data = response.json()
                    # Ensure we returned a valid fee-bump response structure
                    if "xdr" in data or "hash" in data:
                        response.success()
                    else:
                        response.failure("Response JSON missing both 'xdr' and 'hash' fields")
                except Exception as e:
                    response.failure(f"Failed to parse JSON response: {str(e)}")
            else:
                response.failure(f"Unexpected HTTP {response.status_code}: {response.text}")
