/**
 * Sandbox data cleanup service (#717)
 *
 * Purges stale transaction and related records generated by sandbox tenants.
 * Sandbox keys are identified via ApiKey.isSandbox = true.
 */

import { createLogger, serializeError } from "../utils/logger";
import prisma from "../utils/db";

const logger = createLogger({ component: "sandbox_cleanup" });

export interface SandboxCleanupReport {
  runAt: string;
  retentionDays: number;
  cutoffDate: string;
  sandboxTenantCount: number;
  transactionsDeleted: number;
  sponsoredTransactionsDeleted: number;
  webhookDeliveriesDeleted: number;
  durationMs: number;
  status: "SUCCESS" | "FAILED" | "DISABLED";
  error?: string;
}

export interface SandboxCleanupOptions {
  /** Days to retain sandbox transaction data (default: 7). */
  retentionDays?: number;
  /** Batch size for deleteMany loops (default: 500). */
  batchSize?: number;
  /** Override "now" for deterministic tests. */
  now?: Date;
}

const apiKeyModel = (prisma as any).apiKey as {
  findMany: (args: any) => Promise<Array<{ tenantId: string }>>;
};

const transactionModel = (prisma as any).transaction as {
  deleteMany: (args: any) => Promise<{ count: number }>;
  findMany: (args: any) => Promise<Array<{ id: string }>>;
};

const sponsoredTransactionModel = (prisma as any).sponsoredTransaction as {
  deleteMany: (args: any) => Promise<{ count: number }>;
};

const webhookDeliveryModel = (prisma as any).webhookDelivery as {
  deleteMany: (args: any) => Promise<{ count: number }>;
};

export async function getSandboxTenantIds(): Promise<string[]> {
  const keys = await apiKeyModel.findMany({
    where: { isSandbox: true, active: true },
    select: { tenantId: true },
  });

  return [...new Set(keys.map((k) => k.tenantId))];
}

export function calculateSandboxCutoff(
  retentionDays: number,
  now: Date = new Date(),
): Date {
  const cutoff = new Date(now);
  cutoff.setDate(cutoff.getDate() - retentionDays);
  return cutoff;
}

/**
 * Delete all sandbox transaction data for a single tenant (used by manual reset).
 */
export async function purgeSandboxTenantData(
  tenantId: string,
): Promise<{ transactionsDeleted: number; sponsoredDeleted: number; webhookDeliveriesDeleted: number }> {
  const [txResult, sponsoredResult, webhookResult] = await Promise.all([
    transactionModel.deleteMany({ where: { tenantId } }),
    sponsoredTransactionModel.deleteMany({ where: { tenantId } }),
    webhookDeliveryModel.deleteMany({ where: { tenantId } }),
  ]);

  return {
    transactionsDeleted: txResult.count,
    sponsoredDeleted: sponsoredResult.count,
    webhookDeliveriesDeleted: webhookResult.count,
  };
}

/**
 * Purge sandbox transaction data older than the retention window.
 */
export async function purgeStaleSandboxTransactionData(
  options: SandboxCleanupOptions = {},
): Promise<SandboxCleanupReport> {
  const startTime = Date.now();
  const retentionDays =
    options.retentionDays ??
    parsePositiveInt(process.env.SANDBOX_DATA_RETENTION_DAYS, 7);
  const batchSize =
    options.batchSize ??
    parsePositiveInt(process.env.SANDBOX_CLEANUP_BATCH_SIZE, 500);
  const now = options.now ?? new Date();
  const cutoff = calculateSandboxCutoff(retentionDays, now);
  const cutoffIso = cutoff.toISOString();

  let transactionsDeleted = 0;
  let sponsoredTransactionsDeleted = 0;
  let webhookDeliveriesDeleted = 0;
  let status: SandboxCleanupReport["status"] = "FAILED";
  let errorMsg: string | undefined;

  try {
    const tenantIds = await getSandboxTenantIds();

    if (tenantIds.length === 0) {
      status = "SUCCESS";
      logger.info("No active sandbox tenants — cleanup skipped");
      return buildReport({
        retentionDays,
        cutoffIso,
        sandboxTenantCount: 0,
        transactionsDeleted: 0,
        sponsoredTransactionsDeleted: 0,
        webhookDeliveriesDeleted: 0,
        durationMs: Date.now() - startTime,
        status,
      });
    }

    logger.info(
      { tenantIds: tenantIds.length, cutoff: cutoffIso, retentionDays, batchSize },
      "Starting sandbox data cleanup cycle",
    );

    // Delete stale transactions in batches to avoid long locks
    while (true) {
      const batch = await transactionModel.findMany({
        where: {
          tenantId: { in: tenantIds },
          createdAt: { lt: cutoff },
        },
        select: { id: true },
        take: batchSize,
      });

      if (batch.length === 0) break;

      const ids = batch.map((row) => row.id);
      const result = await transactionModel.deleteMany({
        where: { id: { in: ids } },
      });
      transactionsDeleted += result.count;
    }

    const sponsoredResult = await sponsoredTransactionModel.deleteMany({
      where: {
        tenantId: { in: tenantIds },
        createdAt: { lt: cutoff },
      },
    });
    sponsoredTransactionsDeleted = sponsoredResult.count;

    const webhookResult = await webhookDeliveryModel.deleteMany({
      where: {
        tenantId: { in: tenantIds },
        createdAt: { lt: cutoff },
      },
    });
    webhookDeliveriesDeleted = webhookResult.count;

    status = "SUCCESS";
    logger.info(
      {
        transactionsDeleted,
        sponsoredTransactionsDeleted,
        webhookDeliveriesDeleted,
        sandboxTenantCount: tenantIds.length,
      },
      "Sandbox data cleanup cycle complete",
    );
  } catch (err: unknown) {
    const serialized = serializeError(err);
    errorMsg = serialized.message ?? String(err);
    logger.error({ ...serialized }, "Sandbox data cleanup cycle failed");
  }

  const tenantIds = await getSandboxTenantIds().catch(() => []);

  return buildReport({
    retentionDays,
    cutoffIso,
    sandboxTenantCount: tenantIds.length,
    transactionsDeleted,
    sponsoredTransactionsDeleted,
    webhookDeliveriesDeleted,
    durationMs: Date.now() - startTime,
    status,
    error: errorMsg,
  });
}

function buildReport(
  fields: Omit<SandboxCleanupReport, "runAt">,
): SandboxCleanupReport {
  return {
    runAt: new Date().toISOString(),
    ...fields,
  };
}

function parsePositiveInt(value: string | undefined, fallback: number): number {
  if (!value) return fallback;
  const parsed = Number.parseInt(value, 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}
